# uncomment this line when in development
local_backend: true

backend:
  name: github
  repo: service-design-tools/sdt-website
  branch: master


media_folder: "assets/images/uploads"

collections:
# tools config fields
  - label: "tools"
    name: "tools"
    label_singular: "tool"
    description: "Section to manage the tools."
    editor:
      preview: false
    folder: "_tools"
    extension: "md"
    format: "frontmatter"
    create: true
    fields:
      - {label: "title", name: "title", widget: "string"}
      - {label: "subtitle", name: "subtitle", widget: "string"}
      - {label: "show on tools page", name: "publicable", widget: "boolean", default: true}
      - {label: "is this an enhanced tool?", name: "isEnhanced", widget: "boolean", default: false}
      - label: "tool properties"
        name: "properties"
        widget: "object"
        fields:
          - label: "when"
            name: "when"
            widget: "select"
            multiple: true
            options: ["Evaluation", "Ideation", "Implementation", "Prototyping", "Research"]
          - label: "who"
            name: "who"
            widget: "select"
            multiple: true
            options: ["Experts", "Service Staff", "Stakeholders", "Users"]
          - label: "what"
            name: "what"
            widget: "select"
            multiple: true
            options: ["Context", "Experience", "Offering", "System"]
          - label: "how"
            name: "how"
            widget: "select"
            multiple: true
            options: ["Narrative", "Map", "Simulation", "Text"]
      - {label: "also called (for normal tools) or inspired by (for enhanced tools)", name: "synonyms", widget: "string", required: false}
      - {label: "svg icon", name: "icon", widget: "text", hint: "Paste here the svg code of the icon."}
      - label: "related content"
        name: "related"
        widget: "object"
        fields:
          - label: "tools"
            name: "tools"
            widget: "list"
            required: false
            hint: "Before publishing, remove any entry that might have been left empty"
            field:
              label: "tool name"
              name: "tool"
              widget: "relation"
              collection: "tools"
              search_fields: ["title", "properties.when", "properties.who", "properties.what", "properties.how"]
              value_field: "title"
          - label: "tutorials"
            name: "tutorials"
            widget: "list"
            required: false
            hint: "Before publishing, remove any entry that might have been left empty"
            field:
              label: "tutorial name"
              name: "tutorial"
              widget: "relation"
              collection: "tutorials"
              search_fields: ["title"]
              value_field: "title"
          - label: "oblotips"
            name: "tips"
            widget: "list"
            required: false
            hint: "Before publishing, remove any entry that might have been left empty"
            fields:
              - {label: "title", name: "title", widget: "string"}
              - {label: "link", name: "link", widget: "string", hint: "Must be a proper url (make sure it works)"}
      - {label: "description - what it is", name: "body", widget: "markdown"}
      - {label: "description - use it to", name: "use", widget: "markdown"}
      - {label: "description - remember to", name: "reminder", widget: "markdown"}
      - label: "template"
        name: "template"
        widget: "object"
        required: false
        fields:
          - {label: "image", name: "image", widget: "image", hint: "Preview image on website", required: false}
          - {label: "file", name: "file", widget: "file", hint: "File that will be downloaded", required: false}
      - {label: "poster", name: "poster", widget: "file", required: false}
      - label: "how to use steps"
        name: "guidelines"
        widget: "list"
        required: false
        hint: "Before publishing, remove any entry that might have been left empty"
        fields:
          - {label: "step text", name: "step", widget: "markdown"}
          - {label: "pay attention text", name: "warning", widget: "markdown", required: false}
      - label: "references"
        name: "references"
        widget: "list"
        required: false
        hint: "Before publishing, remove any entry that might have been left empty"
        fields:
          - {label: "name", name: "name", widget: "string"}
          - {label: "link", name: "link", widget: "string", hint: "Must be a proper url (make sure it works)", required: false}
      - {label: "image for social networks", name: "socialimage", widget: image, hint: "To be correctly recognized by both Facebook and Twitter, image must be 1200x630 pixels and less than 1MB in size."}

# tutorials config fields
  - label: "tutorials"
    name: "tutorials"
    label_singular: "tutorial"
    description: "Section to manage the tutorials."
    editor:
      preview: false
    folder: "_tutorials"
    extension: "md"
    format: "frontmatter"
    create: true
    fields:
      - {label: "title", name: "title", widget: "string"}
      - {label: "subtitle", name: "subtitle", widget: "string", required: false}
      - {label: "category", name: "category", widget: "string", hint: "Basics, thematic or other"}
      - {label: "introduction text", name: "intro", widget: "markdown", hint: "Brief introduction text that will be shown in the header of the tutorial", required: false}
      - label: "steps"
        name: "steps"
        widget: "list"
        required: false
        hint: "Before publishing, remove any entry that might have been left empty"
        fields:
          - {label: "step title", name: "title", widget: "string"}
          - {label: "description", name: "description", widget: "markdown"}
          - {label: "tips", name: "tips", widget: "markdown"}
          - label: "main tool"
            name: "tool"
            widget: "relation"
            collection: "tools"
            search_fields: ["title", "properties.when", "properties.who", "properties.what", "properties.how"]
            value_field: "title"
            required: false
      - label: "toolkit"
        name: "toolkit"
        widget: "object"
        required: false
        fields:
          - {label: "image", name: "image", widget: "image", hint: "Preview image on website", required: false}
          - {label: "pdf", name: "pdf", widget: "file", hint: "File that will be downloaded", required: false}
      - label: "references"
        name: "references"
        widget: "list"
        required: false
        hint: "Before publishing, remove any entry that might have been left empty"
        fields:
          - {label: "name", name: "name", widget: "string"}
          - {label: "link", name: "link", widget: "string", hint: "Must be a proper url (make sure it works)", required: false}

# case studies config fields
  - label: "case studies"
    name: "case_studies"
    label_singular: "case study"
    description: "Add here all the case studies that need to be referenced throughout the website."
    editor:
      preview: false
    folder: "_case_studies"
    extension: "yml"
    format: "yaml-frontmatter"
    create: true
    fields:
    # add a field for typology of case study: contributed or found
      - {label: "title", name: "title", widget: "string"}
      - {label: "subtitle", name: "subtitle", widget: "string"}
      - {label: "link", name: "link", widget: "string", hint: "Must be a proper url (make sure it works)", required: false}
      - {label: "typology", name: "typology", widget: "select", options: ["contributed from others", "written by oblo"]}
      - label: "related tool"
        name: "tool"
        widget: "relation"
        collection: "tools"
        search_fields: ["title", "properties.when", "properties.who", "properties.what", "properties.how"]
        value_field: "title"
      - label: "company"
        name: "company"
        widget: "object"
        fields:
          - {label: "name", name: "name", widget: "string"}
          - {label: "link", name: "link", widget: "string", hint: "Must be a proper url (make sure it works)"}
      - {label: "description", name: "description", widget: "markdown", hint: "Pay attention to max character limit"} 
      - {label: "what was interesting", name: "insights", widget: "markdown"}
      - label: "images"
        name: "images"
        widget: "list"
        hint: "Before publishing, remove any entry that might have been left empty"
        field: {label: "image", name: "image", widget: image, hint: "Pay attention to dimension, size, format and compression of the image, because it will impact the performance of the website."}

# about config fields
  - label: "about page"
    name: "about-page"
    description: "Here you can edit the content of the About page"
    delete: false
    editor:
      preview: false
    files:
      - label: "about"
        name: "about"
        file: "_data/about.yml"
        fields:
          - label: "timeline"
            name: "timeline"
            widget: "object"
            fields:
              - {label: "title", name: "title", widget: "string", default: "A long journey"}
              - {label: "description", name: "description", widget: "markdown"}
              - label: "event"
                name: "events"
                widget: "list"
                hint: "Before publishing, remove any entry that might have been left empty"
                fields:
                  - {label: "year", name: "year", widget: "string"}
                  - {label: "text", name: "text", widget: "markdown"}
          - label: "team"
            name: "team"
            widget: "object"
            fields:
              - {label: "title", name: "title", widget: "string", default: "Meet our team"}
              - {label: "description", name: "description", widget: "markdown"}
              - label: "member"
                name: "members"
                widget: "list"
                hint: "Before publishing, remove any entry that might have been left empty"
                fields:
                  - {label: "name", name: "name", widget: "string"}
                  - {label: "role", name: "role", widget: "string"}
                  - {label: "picture", name: "picture", widget: "image", hint: "Pay attention to dimension, size, format and compression of the image, because it will impact the performance of the website."}
          - label: "current collaborators"
            name: "collaboratorsCurrent"
            widget: "object"
            fields:
              - {label: "title", name: "title", widget: "string", default: "Current Collaborators"}
              - {label: "description", name: "description", widget: "markdown"}
              - label: "member"
                name: "members"
                widget: "list"
                hint: "Before publishing, remove any entry that might have been left empty"
                fields:
                  - {label: "name", name: "name", widget: "string"}
                  - {label: "role", name: "role", widget: "string"}
                  - {label: "picture", name: "picture", widget: "image", hint: "Pay attention to dimension, size, format and compression of the image, because it will impact the performance of the website.", required: false}
          - label: "past collaborator"
            name: "collaboratorsPast"
            widget: "list"
            hint: "Before publishing, remove any entry that might have been left empty"
            fields:
              - {label: "name", name: "name", widget: "string"}
              - {label: "role", name: "role", widget: "string"}
          - label: "curator"
            name: "curators"
            widget: "list"
            hint: "Before publishing, remove any entry that might have been left empty"
            fields:
              - {label: "logo", name: "logo", widget: "image", hint: "Pay attention to dimension, size, format and compression of the image, because it will impact the performance of the website."}
              - {label: "description", name: "description", widget: "markdown"}

# tools index config fields
  - label: "tools page"
    name: "tools-page"
    description: "Here you can edit the map of the Tools page"
    delete: false
    editor:
      preview: false
    files:
      - label: "tools map data"
        name: "tools-map"
        file: "_data/tools.yml"
        fields:
          - {label: "map", name: "map", widget: "image", hint: "Pay attention to dimension, size, format and compression of the image, because it will impact the performance of the website."}
          - {label: "original map", name: "file", widget: "file", hint: "Map file that will be downloaded", required: false}

# tutorials index config fields
  - label: "tutorials page"
    name: "tutorials-page"
    description: "Here you can edit the order of tutorials shown in the tutorials page."
    delete: false
    editor:
      preview: false
    files:
      - label: "tutorial list"
        name: "tutorial-list"
        file: "_data/tutorials.yml"
        fields:
          - label: "tutorials"
            name: "tutorial-list"
            widget: "list"
            label_singular: "tutorial"
            required: false
            hint: "Before publishing, remove any entry that might have been left empty"
            fields:
              - label: "tutorial"
                name: "tutorial"
                widget: "relation"
                collection: "tutorials"
                search_fields: ["title"]
                value_field: "title"
                required: false

# resources config fields
  - label: "resources page"
    name: "resources-page"
    description: "Here you can add things to the resources page: Media, Publications, Things we love"
    delete: false
    editor:
      preview: false
    files:
      - label: "media files"
        name: "media"
        file: "_data/media.yml"
        fields:
          - label: "medium"
            name: "medium"
            widget: "list"
            fields:
              - {label: "title", name: "title", widget: "string"}
              - {label: "author/authors", name: "author", widget: "string"}
              - {label: "type", name: "type", widget: "string", hint: "Video, keynote, etc."}
              - {label: "url", name: "url", widget: "string", hint: "Must be a proper url (make sure it works)"}
              - {label: "preview image", name: "image", widget: "image", hint: "Pay attention to dimension, size, format and compression of the image, because it will impact the performance of the website."}
      - label: "publications"
        name: "publications"
        file: "_data/publications.yml"
        fields:
          - label: "publication"
            name: "publication"
            widget: "list"
            fields:
              - {label: "title", name: "title", widget: "string"}
              - {label: "author/authors", name: "author", widget: "string"}
              - {label: "type", name: "type", widget: "string", hint: "Paper, proceedings, book, etc."}
              - {label: "url", name: "url", widget: "string", hint: "Must be a proper url (make sure it works)", required: false}
              - {label: "description", name: "description", widget: "text"}
      - label: "things we love"
        name: "thingswelove"
        file: "_data/thingswelove.yml"
        fields:
          - label: "link"
            name: "link"
            widget: "list"
            fields:
              - {label: "title", name: "title", widget: "string"}
              - label: "type"
                name: "type"
                widget: "select"
                options: ["Toolkit", "Magazine", "Event"]
              - {label: "url", name: "url", widget: "string", hint: "Must be a proper url (make sure it works)"}

# enhanced tools page config fields
  - label: "enhanced tools"
    name: "enhanced-tools"
    description: "Here you can edit the content of the Enhanced tools page and banner"
    delete: false
    editor:
      preview: false
    files:
      - label: "enhanced page"
        name: "enhanced-page"
        file: "_data/enhanced-page.yml"
        fields:
          - {label: "title", name: "title", widget: "string"}
          - {label: "subtitle", name: "subtitle", widget: "string"}
          - {label: "introduction", name: "introduction", widget: "markdown"}
          - {label: "svg image", name: "image", widget: "text", hint: "Paste here the svg code for the main image of the page."}
          - label: "sections"
            label_singular: "section"
            name: "sections"
            widget: "list"
            fields:
              - {label: "title", name: "title", widget: "string"}
              - {label: "question", name: "question", widget: "text", required: false}
              - {label: "content", name: "content", widget: "markdown"}
              - label: "tools"
                label_singular: "tool"
                name: "tools"
                widget: "list"
                required: false
                hint: "Before publishing, remove any entry that might have been left empty"
                field:
                  label: "tool name"
                  name: "tool"
                  widget: "relation"
                  collection: "tools"
                  search_fields: ["title", "properties.when", "properties.who", "properties.what", "properties.how"]
                  value_field: "title"
          - label: "masterclass"
            name: "masterclass"
            widget: "object"
            fields:
              - {label: "title", name: "title", widget: "string"}
              - {label: "description", name: "description", widget: "text"}
              - label: "link"
                name: "link"
                widget: "object"
                fields:
                  - {label: "label", name: "label", widget: "string"}
                  - {label: "url", name: "url", widget: "string", hint: "Must be a proper url (make sure it works)"}
      - label: "enhanced banner"
        name: "enhanced-banner"
        file: "_data/enhanced-banner.yml"
        fields:
          - {label: "label", name: "label", widget: "string"}
          - {label: "title", name: "title", widget: "string"}
          - {label: "subtitle", name: "subtitle", widget: "string"}
          - {label: "button label", name: "button", widget: "string"}


# about config fields
  - label: "miscellaneus"
    name: "miscellaneus"
    description: "Various info (links, etc.)"
    delete: false
    editor:
      preview: false
    files:
      - label: "contribute"
        name: "contribute"
        file: "_data/contribute.yml"
        fields:
          - label: "contribute link"
            name: "link"
            widget: "string"
            hint: "Must be a proper url (make sure it works)"
      - label: "footer"
        name: "footer"
        file: "_data/footer.yml"
        fields:
          - label: "curator list"
            name: "curators"
            widget: "list"
            label_singular: "curator"
            required: false
            hint: "Before publishing, remove any entry that might have been left empty"
            fields:
              - label: "curator"
                name: "curator"
                widget: "object"
                required: false
                fields:
                  - {label: "name", name: "name", widget: "string", hint: "Name shown in footer"}
                  - {label: "url", name: "url", widget: "string", hint: "Must be a proper url (make sure it works)", required: false}
